version: '3'

services:
    brevets:
        build: brevets/.
        command: flask_brevets.py
        ports: 
          - "5001:5000"

    mongo:
        image: mongo:5.0.5
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
          - "27017:27017"